export const LEAD_MC = "xynvordat";
export const LEAD_DISCORD = "nyvordat";

export const SEED_ROLES = [
  { name: "GUI Designer", category: "GUI" },
  { name: "GUI Developer", category: "GUI" },
  { name: "HUD Designer", category: "GUI" },
  { name: "HUD Developer", category: "GUI" },
  { name: "Theme Manager", category: "GUI" },
  { name: "Font / Text Renderer", category: "GUI" },
  { name: "AimAssist Developer", category: "Combat" },
  { name: "AutoClicker Developer", category: "Combat" },
  { name: "Reach / Velocity Engineer", category: "Combat" },
  { name: "Killaura / SilentAura Developer", category: "Combat" },
  { name: "WTap / BlockHit / Sprint Developer", category: "Combat" },
  { name: "Right Clicker / KeepSprint Developer", category: "Combat" },
  { name: "Fly Developer", category: "Movement" },
  { name: "Timer / NoSlowdown Engineer", category: "Movement" },
  { name: "SafeWalk / Parkour Engineer", category: "Movement" },
  { name: "Scaffold Developer", category: "Movement" },
  { name: "Clutch / MLG / Blink Developer", category: "Movement" },
  { name: "BackTrack / FakeLag / Freecam Developer", category: "Movement" },
  { name: "ESP Developer", category: "Render" },
  { name: "Chams Developer", category: "Render" },
  { name: "NameTags / Indicators Developer", category: "Render" },
  { name: "HitSelect / Health / Arrows Developer", category: "Render" },
  { name: "AntiDebuff / Explosions Developer", category: "Render" },
  { name: "Projectiles / Target Info Developer", category: "Render" },
  { name: "AntiBot Developer", category: "Utility" },
  { name: "Inventory Manager", category: "Utility" },
  { name: "AutoPot / Throw Manager", category: "Utility" },
  { name: "Xray / Search / HitBoxes Developer", category: "Utility" },
  { name: "AutoArmor / AutoTool / FastPlace Developer", category: "Utility" },
  { name: "Macros / Alt Manager / Profiles Developer", category: "Utility" },
  { name: "Injection Specialist", category: "Core" },
  { name: "Packet / Network Engineer", category: "Core" },
  { name: "Anti-Detection Engineer", category: "Core" },
  { name: "Command System Developer", category: "Core" },
  { name: "Config / Save System Developer", category: "Core" },
  { name: "Testing & Release Engineer", category: "Core" },
];

export const LEAD_ROLES = [
  "GUI Designer", "GUI Developer", "HUD Designer",
  "HUD Developer", "Theme Manager", "Font / Text Renderer",
];

export const SEED_MODULES = [
  { name: "AimAssist", category: "Combat" },
  { name: "AutoClicker", category: "Combat" },
  { name: "BlockHit", category: "Combat" },
  { name: "KeepSprint", category: "Combat" },
  { name: "Killaura", category: "Combat" },
  { name: "Reach", category: "Combat" },
  { name: "Right Clicker", category: "Combat" },
  { name: "SilentAura", category: "Combat" },
  { name: "Sprint", category: "Combat" },
  { name: "Velocity", category: "Combat" },
  { name: "WTap", category: "Combat" },
  { name: "AntiDebuff", category: "Render" },
  { name: "Arrows", category: "Render" },
  { name: "Chams", category: "Render" },
  { name: "ESP", category: "Render" },
  { name: "Explosions", category: "Render" },
  { name: "Fullbright", category: "Render" },
  { name: "Health", category: "Render" },
  { name: "HitSelect", category: "Render" },
  { name: "Indicators", category: "Render" },
  { name: "ItemESP", category: "Render" },
  { name: "NameTags", category: "Render" },
  { name: "Projectiles", category: "Render" },
  { name: "StorageESP", category: "Render" },
  { name: "Target Info", category: "Render" },
  { name: "Alt Manager", category: "Utility" },
  { name: "AntiBot", category: "Utility" },
  { name: "AntiFireball", category: "Utility" },
  { name: "AutoArmor", category: "Utility" },
  { name: "AutoFish", category: "Utility" },
  { name: "AutoHotbar", category: "Utility" },
  { name: "AutoPearl", category: "Utility" },
  { name: "ChestSteal", category: "Utility" },
  { name: "FastPlace", category: "Utility" },
  { name: "Friends", category: "Utility" },
  { name: "HitBoxes", category: "Utility" },
  { name: "InvCleaner", category: "Utility" },
  { name: "InvWalk", category: "Utility" },
  { name: "InventoryManager", category: "Utility" },
  { name: "Macros", category: "Utility" },
  { name: "MurdererFinder", category: "Utility" },
  { name: "NoFall", category: "Utility" },
  { name: "Panic", category: "Utility" },
  { name: "Profiles", category: "Utility" },
  { name: "PropHunt", category: "Utility" },
  { name: "Refill", category: "Utility" },
  { name: "Search", category: "Utility" },
  { name: "ThrowDebuff", category: "Utility" },
  { name: "Throwpot", category: "Utility" },
  { name: "Xray", category: "Utility" },
  { name: "BackTrack", category: "Movement" },
  { name: "Blink", category: "Movement" },
  { name: "Clutch", category: "Movement" },
  { name: "FakeLag", category: "Movement" },
  { name: "Fly", category: "Movement" },
  { name: "Freecam", category: "Movement" },
  { name: "MLG", category: "Movement" },
  { name: "Parkour", category: "Movement" },
  { name: "SafeWalk", category: "Movement" },
  { name: "Scaffold", category: "Movement" },
  { name: "Timer", category: "Movement" },
  { name: "Anti-AFK", category: "World" },
  { name: "AutoTool", category: "World" },
  { name: "Block-In", category: "World" },
  { name: "BedBreaker", category: "World" },
  { name: "BedPlates", category: "World" },
  { name: "ArmorSwitch", category: "Inventory" },
];

export const SEED_TIMELINE = [
  { phase: 1, title: "Phase 1 — Injection Foundation", order: 1, desc: "DLL injection, JNI bridge, classloader hooks, packet interceptors, event system, command framework. Core infrastructure." },
  { phase: 1, title: "ClickGUI Foundation", order: 2, desc: "Basic panel system, component rendering, window dragging, button and slider elements." },
  { phase: 1, title: "Phase 1 Complete", order: 3, desc: "Injection working, basic GUI functional, packet system live, command framework ready." },
  { phase: 2, title: "Phase 2 — Core Modules", order: 1, desc: "Killaura, AimAssist, AutoClicker, Reach, Velocity, Scaffold, ESP, Chams, NameTags." },
  { phase: 2, title: "HUD & Theme System", order: 2, desc: "Watermark, array list, keystrokes, CPS display, potion HUD. Theme presets." },
  { phase: 2, title: "Phase 2 Complete", order: 3, desc: "Core combat + render modules functional. HUD live with theme support." },
  { phase: 3, title: "Phase 3 — Expansion", order: 1, desc: "Movement, Utility, and World modules. Broadening Glacier's capability." },
  { phase: 3, title: "Config & Profiles", order: 2, desc: "Save/load system, profile switching, import/export. Alt manager, friends list." },
  { phase: 3, title: "Phase 3 Complete", order: 3, desc: "Full feature suite. 60+ modules operational. Beta release." },
  { phase: 4, title: "Phase 4 — Anti-Detection & Release", order: 1, desc: "Bypass testing, randomization passes, signature obfuscation, packet normalization." },
  { phase: 4, title: "Testing & Bug Fixes", order: 2, desc: "Full QA pass, edge cases, crash fixes, performance optimization." },
  { phase: 4, title: "Glacier Launch", order: 3, desc: "Public release. Version 1.0. Documentation, distribution, community setup." },
];
